name: build and run
on: [push]
jobs: 
    build:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/chechout@v4
            - run: g++ main.cpp my_add.cpp -o main
            - run: ./main 4 6